
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 17 18:35:00 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IGUALES = 40;
  public static final int CHAR = 5;
  public static final int CORCHETE_CERRADO = 21;
  public static final int RESTA = 43;
  public static final int DIFERENTES = 41;
  public static final int INT = 2;
  public static final int PARENTESIS_ABIERTO = 11;
  public static final int FOR = 26;
  public static final int LLAVE_ABIERTA = 9;
  public static final int IDENTIFICADOR = 7;
  public static final int IGUAL = 14;
  public static final int ARRAY_NUMBER = 52;
  public static final int BOOL = 4;
  public static final int INCREMENTO = 53;
  public static final int SUMA = 42;
  public static final int MAIN = 31;
  public static final int IF = 22;
  public static final int PUNTO_COMA = 13;
  public static final int CORCHETE_ABIERTO = 20;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int TRUE = 32;
  public static final int DECREMENTO = 54;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int MODULO = 46;
  public static final int LITERAL_CHAR = 18;
  public static final int NEGACION = 34;
  public static final int MAYOR_QUE = 38;
  public static final int BREAK = 35;
  public static final int OPERADOR_NEGATIVO = 55;
  public static final int ERROR = 48;
  public static final int LITERAL_FLOAT = 16;
  public static final int POTENCIA = 47;
  public static final int LITERAL_INT = 15;
  public static final int ELSE = 24;
  public static final int READ = 29;
  public static final int LITERAL_STRING = 19;
  public static final int WHILE = 25;
  public static final int MAYOR_IGUAL = 39;
  public static final int FLOAT = 3;
  public static final int CONJUNCION = 49;
  public static final int LITERAL_BOOL = 17;
  public static final int STRING = 6;
  public static final int PARENTESIS_CERRADO = 12;
  public static final int MENOR_QUE = 36;
  public static final int LLAVE_CERRADA = 10;
  public static final int DISYUNCION = 50;
  public static final int MENOR_IGUAL = 37;
  public static final int FALSE = 33;
  public static final int DIVISION = 45;
  public static final int DOLAR = 51;
  public static final int ELIF = 23;
  public static final int PRINT = 30;
  public static final int DO = 27;
  public static final int MULTIPLICACION = 44;
}

