
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 19 12:14:06 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IGUALES = 39;
  public static final int CHAR = 5;
  public static final int CORCHETE_CERRADO = 20;
  public static final int RESTA = 42;
  public static final int DIFERENTES = 40;
  public static final int INT = 2;
  public static final int PARENTESIS_ABIERTO = 11;
  public static final int FOR = 25;
  public static final int LLAVE_ABIERTA = 9;
  public static final int IDENTIFICADOR = 7;
  public static final int IGUAL = 14;
  public static final int ARRAY_NUMBER = 51;
  public static final int BOOL = 4;
  public static final int INCREMENTO = 52;
  public static final int SUMA = 41;
  public static final int MAIN = 30;
  public static final int IF = 21;
  public static final int PUNTO_COMA = 13;
  public static final int CORCHETE_ABIERTO = 19;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int TRUE = 31;
  public static final int DECREMENTO = 53;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int MODULO = 45;
  public static final int LITERAL_CHAR = 17;
  public static final int NEGACION = 33;
  public static final int MAYOR_QUE = 37;
  public static final int BREAK = 34;
  public static final int ERROR = 47;
  public static final int LITERAL_FLOAT = 16;
  public static final int POTENCIA = 46;
  public static final int LITERAL_INT = 15;
  public static final int ELSE = 23;
  public static final int READ = 28;
  public static final int LITERAL_STRING = 18;
  public static final int WHILE = 24;
  public static final int MAYOR_IGUAL = 38;
  public static final int FLOAT = 3;
  public static final int CONJUNCION = 48;
  public static final int STRING = 6;
  public static final int PARENTESIS_CERRADO = 12;
  public static final int MENOR_QUE = 35;
  public static final int LLAVE_CERRADA = 10;
  public static final int DISYUNCION = 49;
  public static final int MENOR_IGUAL = 36;
  public static final int FALSE = 32;
  public static final int DIVISION = 44;
  public static final int DOLAR = 50;
  public static final int ELIF = 22;
  public static final int PRINT = 29;
  public static final int DO = 26;
  public static final int MULTIPLICACION = 43;
}

