
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 29 21:25:29 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IGUALES = 38;
  public static final int CHAR = 5;
  public static final int CORCHETE_CERRADO = 19;
  public static final int RESTA = 41;
  public static final int DIFERENTES = 39;
  public static final int INT = 2;
  public static final int PARENTESIS_ABIERTO = 11;
  public static final int FOR = 24;
  public static final int LLAVE_ABIERTA = 9;
  public static final int IDENTIFICADOR = 7;
  public static final int IGUAL = 13;
  public static final int BOOL = 4;
  public static final int INCREMENTO = 50;
  public static final int SUMA = 40;
  public static final int MAIN = 29;
  public static final int IF = 20;
  public static final int CORCHETE_ABIERTO = 18;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int TRUE = 30;
  public static final int DECREMENTO = 51;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int MODULO = 44;
  public static final int LITERAL_CHAR = 16;
  public static final int NEGACION = 32;
  public static final int MAYOR_QUE = 36;
  public static final int BREAK = 33;
  public static final int ERROR = 46;
  public static final int LITERAL_FLOAT = 15;
  public static final int POTENCIA = 45;
  public static final int LITERAL_INT = 14;
  public static final int ELSE = 22;
  public static final int READ = 27;
  public static final int LITERAL_STRING = 17;
  public static final int WHILE = 23;
  public static final int MAYOR_IGUAL = 37;
  public static final int FLOAT = 3;
  public static final int CONJUNCION = 47;
  public static final int STRING = 6;
  public static final int PARENTESIS_CERRADO = 12;
  public static final int LLAVE_CERRADA = 10;
  public static final int MENOR_QUE = 34;
  public static final int DISYUNCION = 48;
  public static final int MENOR_IGUAL = 35;
  public static final int FALSE = 31;
  public static final int DIVISION = 43;
  public static final int DOLAR = 49;
  public static final int ELIF = 21;
  public static final int PRINT = 28;
  public static final int DO = 25;
  public static final int MULTIPLICACION = 42;
}

